"""
NarrateKPI — Email Dispatch Engine (Module 4)

Converts Markdown reports to email-safe HTML with inlined CSS suitable for
Gmail/Outlook, then dispatches via the Resend API.

Delivery chain (tried in order):
  1. ``resend`` Python SDK (if installed)
  2. ``httpx`` direct HTTP call to ``https://api.resend.com/emails``
  3. Dry-run — logs the email to ``./email_output/`` and prints to console

When ``RESEND_API_KEY`` is not set, the engine always falls to dry-run mode
without making any network calls.
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path
from typing import Optional

logger = logging.getLogger("narratekpi.email")


# ──────────────────────────────────────────────────────────────────────
#  Configuration
# ──────────────────────────────────────────────────────────────────────

RESEND_API_KEY: Optional[str] = os.environ.get("RESEND_API_KEY")

# Support both FROM_EMAIL (shorter) and DEFAULT_FROM_EMAIL (legacy).
# FROM_EMAIL takes precedence.
DEFAULT_FROM_EMAIL: str = (
    os.environ.get("FROM_EMAIL")
    or os.environ.get("DEFAULT_FROM_EMAIL")
    or "reports@narratekpi.com"
)

RESEND_API_URL: str = "https://api.resend.com/emails"


# ──────────────────────────────────────────────────────────────────────
#  Markdown → HTML (email-safe, inline CSS)
# ──────────────────────────────────────────────────────────────────────

_EMAIL_CSS = """
    body { margin:0; padding:0; background-color:#f4f4f5; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; }
    .email-wrap { max-width:600px; margin:0 auto; padding:24px; background:#ffffff; }
    .email-header { border-bottom:2px solid #6366f1; padding-bottom:16px; margin-bottom:20px; }
    .email-header h1 { font-size:20px; font-weight:700; color:#18181b; margin:0 0 4px 0; }
    .email-header p { font-size:13px; color:#71717a; margin:0; }
    .email-body { font-size:14px; line-height:1.7; color:#3f3f46; }
    .email-body h2 { font-size:16px; font-weight:700; color:#18181b; margin:20px 0 10px 0; }
    .email-body h3 { font-size:14px; font-weight:600; color:#27272a; margin:16px 0 8px 0; }
    .email-body p { margin:0 0 10px 0; }
    .email-body hr { border:none; border-top:1px solid #e4e4e7; margin:16px 0; }
    .email-body strong { color:#18181b; }
    .email-body blockquote { border-left:3px solid #6366f1; padding:8px 14px; margin:10px 0; background:#f4f4f5; border-radius:0 4px 4px 0; color:#52525b; }
    .email-body code { background:#f4f4f5; padding:2px 6px; border-radius:3px; font-size:13px; color:#6366f1; font-family:'SF Mono','Fira Code',monospace; }
    .email-body pre { background:#f4f4f5; padding:12px 16px; border-radius:6px; overflow-x:auto; font-size:13px; line-height:1.5; }
    .email-body pre code { background:none; padding:0; }
    .email-body ul, .email-body ol { padding-left:20px; margin:0 0 10px 0; }
    .email-body li { margin-bottom:4px; }
    .email-body a { color:#6366f1; text-decoration:underline; }
    .email-footer { border-top:1px solid #e4e4e7; padding-top:16px; margin-top:24px; font-size:12px; color:#a1a1aa; text-align:center; }
"""


def _markdown_to_email_html(markdown_text: str) -> str:
    """Convert Markdown to full email HTML document with inline CSS."""
    try:
        import markdown2
    except ImportError:
        # Fallback: convert basic Markdown manually for essential formatting.
        body_html = _basic_markdown_to_html(markdown_text)
    else:
        extras = ["fenced-code-blocks", "tables", "break-on-newline"]
        body_html = markdown2.markdown(markdown_text, extras=extras)

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<style>{_EMAIL_CSS}</style></head>
<body>
<div class="email-wrap">
  <div class="email-header">
    <h1>NarrateKPI — Performance Report</h1>
    <p>Automated agency report generated by NarrateKPI</p>
  </div>
  <div class="email-body">{body_html}</div>
  <div class="email-footer">
    <p>Generated by NarrateKPI • AI-Driven Agency Report Automation</p>
  </div>
</div>
</body>
</html>"""


def _basic_markdown_to_html(text: str) -> str:
    """Minimal Markdown-to-HTML converter for when markdown2 is not installed.

    Produces clean block-level HTML (no ``<p>`` wrappers around headings,
    blockquotes, or lists) so email clients don't strip or misrender content.
    """
    import html as html_mod
    import re

    lines = text.split("\n")
    out: list[str] = []
    in_list = False
    in_paragraph = False

    def _close_para() -> None:
        nonlocal in_paragraph
        if in_paragraph:
            out.append("</p>")
            in_paragraph = False

    def _close_list() -> None:
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    def _emit_para_line(stripped: str) -> None:
        nonlocal in_paragraph
        content = html_mod.escape(stripped)
        content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
        content = re.sub(r"`(.+?)`", r"<code>\1</code>", content)
        if not in_paragraph:
            out.append("<p>")
            in_paragraph = True
            out.append(content)
        else:
            out.append(f"<br>{content}")

    for line in lines:
        stripped = line.strip()

        # Heading
        h_match = re.match(r"^##\s+(.+)$", stripped)
        if h_match:
            _close_para()
            _close_list()
            out.append(f"<h2>{html_mod.escape(h_match.group(1))}</h2>")
            continue
        h3_match = re.match(r"^###\s+(.+)$", stripped)
        if h3_match:
            _close_para()
            _close_list()
            out.append(f"<h3>{html_mod.escape(h3_match.group(1))}</h3>")
            continue

        # Horizontal rule
        if stripped.startswith("---"):
            _close_para()
            _close_list()
            out.append("<hr>")
            continue

        # Blockquote
        if stripped.startswith("> "):
            _close_para()
            _close_list()
            out.append(f"<blockquote>{html_mod.escape(stripped[2:])}</blockquote>")
            continue

        # Unordered list item
        if stripped.startswith("- ") or stripped.startswith("* "):
            _close_para()
            if not in_list:
                out.append("<ul>")
                in_list = True
            content = html_mod.escape(stripped[2:])
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            out.append(f"<li>{content}</li>")
            continue

        # Ordered list item
        ol_match = re.match(r"^\d+\.\s+(.+)$", stripped)
        if ol_match:
            _close_para()
            if not in_list:
                out.append("<ol>")
                in_list = True
            content = html_mod.escape(ol_match.group(1))
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            out.append(f"<li>{content}</li>")
            continue

        # End of list on non-list line
        if in_list:
            _close_list()

        # Empty line — close paragraph
        if not stripped:
            _close_para()
            continue

        # Regular paragraph content
        _emit_para_line(stripped)

    _close_para()
    _close_list()
    return "".join(out)


# ──────────────────────────────────────────────────────────────────────
#  Resend SDK dispatch
# ──────────────────────────────────────────────────────────────────────


def _send_via_resend_sdk(
    api_key: str,
    from_email: str,
    to_email: str,
    subject: str,
    html_body: str,
) -> bool:
    """Send email via the official ``resend`` Python SDK.

    Falls back to ``httpx`` if the SDK is not installed.
    """
    try:
        import resend
    except ImportError:
        logger.info(
            "[NarrateKPI] ⚠️  resend SDK not installed — falling back to httpx. "
            "Install it with: pip install resend"
        )
        return _send_via_httpx(api_key, from_email, to_email, subject, html_body)

    resend.api_key = api_key

    params = {
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html_body,
    }

    try:
        response = resend.Emails.send(params)
        email_id = getattr(response, "id", str(response)[:20])
        logger.info("[NarrateKPI] ✅ Email sent via Resend SDK to %s — ID: %s", to_email, email_id)
        return True
    except Exception as exc:
        logger.error("[NarrateKPI] ❌ Resend SDK failed for %s: %s. Falling back to httpx.", to_email, exc)
        return _send_via_httpx(api_key, from_email, to_email, subject, html_body)


def _send_via_httpx(
    api_key: str,
    from_email: str,
    to_email: str,
    subject: str,
    html_body: str,
) -> bool:
    """Send email via a direct HTTP POST to the Resend REST API."""
    try:
        import httpx
    except ImportError:
        logger.warning(
            "[NarrateKPI] ⚠️  httpx is not installed. Falling back to dry-run mode. "
            "Install it with: pip install httpx"
        )
        return False

    payload = {
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html_body,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(RESEND_API_URL, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()
        logger.info("[NarrateKPI] ✅ Email sent via httpx to %s — Resend ID: %s", to_email, data.get("id", "unknown"))
        return True
    except Exception as exc:
        logger.error("[NarrateKPI] ❌ httpx email send failed to %s: %s", to_email, exc)
        return False


# ──────────────────────────────────────────────────────────────────────
#  Public API
# ──────────────────────────────────────────────────────────────────────


def send_report_email(
    to_email: str,
    subject: str,
    markdown_content: str,
    *,
    from_email: Optional[str] = None,
) -> bool:
    """Convert a Markdown report to HTML and send it via the Resend API.

    Delivery chain:
      1. ``resend`` SDK (if installed)
      2. ``httpx`` direct HTTP call
      3. Dry-run — log to ``./email_output/`` and return ``True``

    Parameters
    ----------
    to_email:
        Recipient email address.
    subject:
        Email subject line.
    markdown_content:
        The Markdown body of the report.
    from_email:
        Sender address; defaults to ``FROM_EMAIL`` or ``DEFAULT_FROM_EMAIL``
        environment variables.

    Returns
    -------
    bool
        ``True`` if the send was successful (or dry-run mode is active),
        ``False`` only if all live delivery methods failed.
    """
    sender = from_email or DEFAULT_FROM_EMAIL
    email_html = _markdown_to_email_html(markdown_content)

    # ── Dry-run / mock mode ───────────────────────────────────────
    if not RESEND_API_KEY:
        _log_dry_run(to_email, subject, email_html)
        return True

    # ── Live delivery: SDK → httpx → dry-run ──────────────────────
    success = _send_via_resend_sdk(
        api_key=RESEND_API_KEY,
        from_email=sender,
        to_email=to_email,
        subject=subject,
        html_body=email_html,
    )

    if success:
        return True

    # All live methods failed — fall back to dry-run logging so the
    # pipeline doesn't break.
    logger.warning(
        "[NarrateKPI] ⚠️  All email delivery methods failed for %s. "
        "Falling back to dry-run logging.",
        to_email,
    )
    _log_dry_run(to_email, subject, email_html)
    return False


# ──────────────────────────────────────────────────────────────────────
#  Dry-run logging
# ──────────────────────────────────────────────────────────────────────


def _log_dry_run(to_email: str, subject: str, email_html: str) -> None:
    """Log the email content locally for debugging."""
    log_path = Path("email_output") / f"email_{to_email.replace('@', '_at_')}.html"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text(email_html, encoding="utf-8")

    preview = email_html[:500].replace("\n", " ")
    logger.info(
        "\n"
        "────────────────────────────────────────────────────────────\n"
        "  [NarrateKPI] 📧 DRY-RUN EMAIL\n"
        "  To:      %s\n"
        "  Subject: %s\n"
        "  Written: %s\n"
        "  Preview: %s...\n"
        "────────────────────────────────────────────────────────────",
        to_email,
        subject,
        log_path.resolve(),
        preview,
    )
    print(
        f"[NarrateKPI] 📧 Dry-run email -> {log_path.resolve()} "
        f"(to={to_email}, subject='{subject}')",
        file=sys.stderr,
    )
